### ISSUE TITLE
Campain

### ISSUE THREAD

**Issue by MACE-Zer0** [ceari/whyattend#45]
Is it possible for the tracket to display provicences owned in the 3rd campain , and battles scheduled ??

anything i can just switch in the config files ?? , or it cant be done ??

Thanks

**Comment by ceari** [comment]
Hey, I just commited a fix to the battle schedule and provinces owned lists.

I'm not sure how to get the campaign provinces and schedule though. Is the 3rd campaign still going on at the moment (I haven't played the game in a while)? Wargaming's clan pages on http://eu.wargaming.net/clans/500016367/provinces/ and http://eu.wargaming.net/clans/500016367/battles/ for example show provinces and scheduled battles for the global map but don't mention a campaign map.

**Comment by enbewu** [comment]
Don't worry mate, campaign is long over. We are currently back to the regular CW.

Good to see you around.

**Comment by ceari** [comment]
Oh, I somehow thought this was a new issue and not from November :D

**Comment by enbewu** [comment]
BTW, I wonder, would you find the time to put couple of new stats to the statistics page?
1) Most owner provinces
2) Most battles per day
3) Highest income per day
4) Summary of income since the start of the time (just count from the update) - don't worry about plundered provinces

What do you think?

I was also lacking recently stats for the players who left the clan - if someone is not very popular and I don't remember him I'm not always sure how active he was.

**Comment by enbewu** [comment]
1) Interesting. That would be OK
2) Yep

**Comment by MACE-Zer0** [comment]
since your update ... list of battles is empty , and cannot add battles , look at log 



  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/whyattend/whyattend/webapp.py", line 152, in decorated_function
    return f(*args, **kwargs)
  File "/var/www/whyattend/whyattend/webapp.py", line 198, in decorated_f
    return f(*args, **kwargs)
  File "/var/www/whyattend/whyattend/webapp.py", line 833, in create_battle
    if battle.stronghold:
AttributeError: 'Battle' object has no attribute 'stronghold'
ERROR:tornado.access:500 POST /battles/create (85.139.93.8) 36.32ms
INFO:whyattend.webapp:Querying Wargaming server for provinces owned by clan 500011869 MACE
INFO:whyattend.webapp:Querying Wargaming server for battle schedule of clan 500011869 MACE
ERROR:whyattend.webapp:Exception on /battles/list/MACE/json [GET]
Traceback (most recent call last):
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/whyattend/whyattend/webapp.py", line 152, in decorated_function
    return f(*args, **kwargs)
  File "/var/www/whyattend/whyattend/webapp.py", line 1020, in battles_list_json
    'aaData': [make_row(battle) for battle in battles]
  File "/var/www/whyattend/whyattend/webapp.py", line 964, in make_row
    if battle.stronghold:
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/sqlalchemy/engine/result.py", line 97, in __getattr__
    raise AttributeError(e.args[0])
AttributeError: Could not locate column in row for column 'stronghold'
ERROR:tornado.access:500 GET /battles/list/MACE/json?sEcho=1&iColumns=14&sColumns=&iDisplayStart=0&iDisplayLength=10&mDataProp_0=0&mDataProp_1=1&mDataProp_2=2&mDataProp_3=3&mDataProp_4=4&mDataProp_5=5&mDataProp_6=6&mDataProp_7=7&mDataProp_8=8&mDataProp_9=9&mDataProp_10=10&mDataProp_11=11&mDataProp_12=12&mDataProp_13=13&sSearch=&bRegex=false&sSearch_0=&bRegex_0=false&bSearchable_0=true&sSearch_1=&bRegex_1=false&bSearchable_1=true&sSearch_2=&bRegex_2=false&bSearchable_2=true&sSearch_3=&bRegex_3=false&bSearchable_3=true&sSearch_4=&bRegex_4=false&bSearchable_4=true&sSearch_5=&bRegex_5=false&bSearchable_5=true&sSearch_6=&bRegex_6=false&bSearchable_6=true&sSearch_7=&bRegex_7=false&bSearchable_7=true&sSearch_8=&bRegex_8=false&bSearchable_8=true&sSearch_9=&bRegex_9=false&bSearchable_9=true&sSearch_10=&bRegex_10=false&bSearchable_10=true&sSearch_11=&bRegex_11=false&bSearchable_11=true&sSearch_12=&bRegex_12=false&bSearchable_12=true&sSearch_13=&bRegex_13=false&bSearchable_13=true&iSortCol_0=1&sSortDir_0=desc&iSortingCols=1&bSortable_0=true&bSortable_1=true&bSortable_2=true&bSortable_3=true&bSortable_4=true&bSortable_5=true&bSortable_6=true&bSortable_7=false&bSortable_8=true&bSortable_9=true&bSortable_10=true&bSortable_11=false&bSortable_12=false&bSortable_13=false&_=1422308049242 (85.139.93.8) 80.96ms

**Comment by MACE-Zer0** [comment]
had to revert back !!!

**Comment by ceari** [comment]
You probably have to run `alembic upgrade head` in the tracker directory with activated virtual env to update your database.

**Comment by MACE-Zer0** [comment]
did alembic gave this error 

sqlalchemy.exc.ArgumentError: Can't load plugin: sqlalchemy.dialects:driver

and now cant load the whyattend


(myenv)ubuntu@ip-172-31-22-252:/var/www/whyattend$ python runtornado.py
Traceback (most recent call last):
  File "runtornado.py", line 4, in <module>
    from whyattend.webapp import app
  File "/var/www/whyattend/whyattend/webapp.py", line 5
    <!DOCTYPE html>

**Comment by MACE-Zer0** [comment]
it worked the alembic upgrade , but now cannot login to whyattend , keeps returning to same login page 


(myenv)ubuntu@ip-172-31-22-252:/var/www/whyattend$ python runtornado.py
INFO:whyattend.webapp:Querying Wargaming server for provinces owned by clan 500011869 MACE
ERROR:whyattend.webapp:Error querying WG server for provinces owned
Traceback (most recent call last):
  File "/var/www/whyattend/whyattend/webapp.py", line 305, in cached_provinces_owned
    return wotapi.get_provinces(clan_id)
  File "/var/www/whyattend/whyattend/wotapi.py", line 79, in get_provinces
    return r.json()
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/requests/models.py", line 651, in json
    return json.loads(self.text or self.content, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
INFO:whyattend.webapp:Querying Wargaming server for battle schedule of clan 500011869 MACE
ERROR:whyattend.webapp:Error querying WG server for battle schedule
Traceback (most recent call last):
  File "/var/www/whyattend/whyattend/webapp.py", line 314, in cached_battle_schedule
    return wotapi.get_battle_schedule(clan_id)
  File "/var/www/whyattend/whyattend/wotapi.py", line 124, in get_battle_schedule
    for item in schedule['items']:
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by MACE-Zer0** [comment]
Its working ... but cannot see the past battle list ... its empty .. but the rest of the stats are there .. just cant see any battles 

can u help ??

http://s15.postimg.org/o6kl71ryz/SCreen.jpg


AttributeError: Could not locate column in row for column 'stronghold'
ERROR:tornado.access:500 GET /battles/list/MACE/json?sEcho=1&iColumns=14&sColumns=&iDisplayStart=0&iDisplayLength=10&mDataProp_0=0&mDataProp_1=1&mDataProp_2=2&mDataProp_3=3&mDataProp_4=4&mDataProp_5=5&mDataProp_6=6&mDataProp_7=7&mDataProp_8=8&mDataProp_9=9&mDataProp_10=10&mDataProp_11=11&mDataProp_12=12&mDataProp_13=13&sSearch=&bRegex=false&sSearch_0=&bRegex_0=false&bSearchable_0=true&sSearch_1=&bRegex_1=false&bSearchable_1=true&sSearch_2=&bRegex_2=false&bSearchable_2=true&sSearch_3=&bRegex_3=false&bSearchable_3=true&sSearch_4=&bRegex_4=false&bSearchable_4=true&sSearch_5=&bRegex_5=false&bSearchable_5=true&sSearch_6=&bRegex_6=false&bSearchable_6=true&sSearch_7=&bRegex_7=false&bSearchable_7=true&sSearch_8=&bRegex_8=false&bSearchable_8=true&sSearch_9=&bRegex_9=false&bSearchable_9=true&sSearch_10=&bRegex_10=false&bSearchable_10=true&sSearch_11=&bRegex_11=false&bSearchable_11=true&sSearch_12=&bRegex_12=false&bSearchable_12=true&sSearch_13=&bRegex_13=false&bSearchable_13=true&iSortCol_0=1&sSortDir_0=desc&iSortingCols=1&bSortable_0=true&bSortable_1=true&bSortable_2=true&bSortable_3=true&bSortable_4=true&bSortable_5=true&bSortable_6=true&bSortable_7=false&bSortable_8=true&bSortable_9=true&bSortable_10=true&bSortable_11=false&bSortable_12=false&bSortable_13=false&_=1422354103793 (85.139.93.8) 88.40ms

**Comment by MACE-Zer0** [comment]
the alembic upgrade head gives this 

(myenv)ubuntu@ip-172-31-22-252:/var/www/whyattend$ alembic upgrade head
Traceback (most recent call last):
  File "/var/www/whyattend/myenv/bin/alembic", line 9, in <module>
    load_entry_point('alembic==0.6.1', 'console_scripts', 'alembic')()
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/alembic/config.py", line 298, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/alembic/config.py", line 293, in main
    self.run_cmd(cfg, options)
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/alembic/config.py", line 279, in run_cmd
    **dict((k, getattr(options, k)) for k in kwarg)
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/alembic/command.py", line 124, in upgrade
    script.run_env()
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/alembic/script.py", line 199, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/alembic/util.py", line 198, in load_python_file
    module = load_module(module_id, path)
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/alembic/compat.py", line 55, in load_module
    mod = imp.load_source(module_id, path, fp)
  File "whyattend/alembic/env.py", line 72, in <module>
    run_migrations_online()
  File "whyattend/alembic/env.py", line 55, in run_migrations_online
    poolclass=pool.NullPool)
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 351, in engine_from_config
    return create_engine(url, **opts)
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 332, in create_engine
    return strategy.create(*args, **kwargs)
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 50, in create
    dialect_cls = u.get_dialect()
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/sqlalchemy/engine/url.py", line 107, in get_dialect
    cls = registry.load(name)
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 142, in load
    (self.group, name))
sqlalchemy.exc.ArgumentError: Can't load plugin: sqlalchemy.dialects:driver

**Comment by ceari** [comment]
Duplicate the `alembic.ini.template` file to `alembic.ini` and change the database URL in the line `sqlalchemy.url = driver://user:pass@localhost/dbname` to your DATABASE_URI from local_config.py

**Comment by MACE-Zer0** [comment]
always something .. now 

sqlalchemy.exc.OperationalError: (OperationalError) (1060, "Duplicate column name 'email'") 'ALTER TABLE player ADD COLUMN email VARCHAR(100)' ()

**Comment by MACE-Zer0** [comment]
im in the database and in player i dont see a duplicate column email

**Comment by MACE-Zer0** [comment]
util.load_python_file(self.dir, 'env.py')
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/alembic/util.py", line 198, in load_python_file
    module = load_module(module_id, path)
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/alembic/compat.py", line 55, in load_module
    mod = imp.load_source(module_id, path, fp)
  File "whyattend/alembic/env.py", line 72, in <module>
    run_migrations_online()
  File "whyattend/alembic/env.py", line 65, in run_migrations_online
    context.run_migrations()
  File "<string>", line 7, in run_migrations
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/alembic/environment.py", line 652, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/alembic/migration.py", line 225, in run_migrations
    change(**kw)
  File "whyattend/alembic/versions/18b90187fbae_add_email_address_to_player.py", line 18, in upgrade
    op.add_column('player', sa.Column('email', sa.String(length=100), default='', nullable=True))
  File "<string>", line 7, in add_column
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/alembic/operations.py", line 365, in add_column
    schema=schema
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/alembic/ddl/impl.py", line 127, in add_column
    self._exec(base.AddColumn(table_name, column, schema=schema))
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/alembic/ddl/impl.py", line 76, in _exec
    conn.execute(construct, *multiparams, **params)
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 720, in _execute_ddl
    compiled
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
    exc_info
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 195, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
sqlalchemy.exc.OperationalError: (OperationalError) (1060, "Duplicate column name 'email'") 'ALTER TABLE player ADD COLUMN email VARCHAR(100)' ()

**Comment by MACE-Zer0** [comment]
have been trying all that i can remember ... dont know why this error is happening .. there is no duplicate email column in database

**Comment by ceari** [comment]
The error means that there already is an email column and the database migration tries to add another one. I'm not sure why your table already has the email column.
Can you please run the SQL query `select * from alembic_version` on your database? alembic stores the identifier of the last migration script it ran in this table, I suspect there's something wrong with that in your DB.

**Comment by MACE-Zer0** [comment]
here is the result

 MySQL returned an empty result set (i.e. zero rows). (Query took 0.0003 sec)
SELECT * 
FROM  `alembic_version` 
WHERE 1 
LIMIT 0 , 30

**Comment by ceari** [comment]
Okay, then we need to find out what state your database is in compared to the alembic migration scripts to fix it. But please create a backup of the database before just in case :-)

Does your 'player' table have a 'phone' column? If it does, please run `alembic stamp 398cf0b7b8c8` which sets the current version followed by `alembic upgrade head` which should create the latest versions for strongholds.

If the "phone" column does not exist yet we need to go back through the migration steps (see whyattend/alembic/versions") until we find the last one that was applied to your database.

**Comment by MACE-Zer0** [comment]
(myenv)ubuntu@ip-172-31-22-252:/var/www/whyattend$ alembic upgrade head
INFO  [alembic.migration] Context impl MySQLImpl.
INFO  [alembic.migration] Will assume non-transactional DDL.

**Comment by MACE-Zer0** [comment]
what next , still doesnt do nothing  ??

**Comment by MACE-Zer0** [comment]
Current revision for mysql://root:XXXXX@localhost/MACE: 37000801b290 -> 398cf0b7b8c8 (head), Player phone number field

**Comment by ceari** [comment]
Do you have the latest source code? There should be a file `whyattend/alembic/versions/2413542ce715_stronghold_support.py` and running `alembic upgrade head` should do something like this:
> INFO  [alembic.migration] Context impl MySQLImpl.
> INFO  [alembic.migration] Will assume non-transactional DDL.
> INFO  [alembic.migration] Running upgrade 398cf0b7b8c8 -> 2413542ce715, Stronghold support

**Comment by MACE-Zer0** [comment]
ok i said exacly like  the text up , but when i try to create a battle it says this


ERROR:whyattend.webapp:Exception on /battles/create [POST]
Traceback (most recent call last):
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/whyattend/whyattend/webapp.py", line 152, in decorated_function
    return f(*args, **kwargs)
  File "/var/www/whyattend/whyattend/webapp.py", line 198, in decorated_f
    return f(*args, **kwargs)
  File "/var/www/whyattend/whyattend/webapp.py", line 833, in create_battle
    if battle.stronghold:
AttributeError: 'Battle' object has no attribute 'stronghold'
ERROR:tornado.access:500 POST /battles/create (85.139.93.8) 26.93ms

**Comment by ceari** [comment]
Well, I'm not really sure what's going on. Does the battle table in the DB now have a "stronghold" column?

**Comment by MACE-Zer0** [comment]
yes it does , last table

**Comment by MACE-Zer0** [comment]
1	id	int(11)			No	None	AUTO_INCREMENT	Change Change	Drop Drop	
Primary Primary
Unique Unique
Index Index
Spatial Spatial
Fulltext Fulltext
Distinct values Distinct values
	2	date	datetime			Yes	NULL		Change Change	Drop Drop	
Primary Primary
Unique Unique
Index Index
Spatial Spatial
Fulltext Fulltext
Distinct values Distinct values
	3	clan	varchar(10)	latin1_swedish_ci		Yes	NULL		Change Change	Drop Drop	
Primary Primary
Unique Unique
Index Index
Spatial Spatial
Fulltext Fulltext
Distinct values Distinct values
	4	enemy_clan	varchar(10)	latin1_swedish_ci		Yes	NULL		Change Change	Drop Drop	
Primary Primary
Unique Unique
Index Index
Spatial Spatial
Fulltext Fulltext
Distinct values Distinct values
	5	victory	tinyint(1)			Yes	NULL		Change Change	Drop Drop	
Primary Primary
Unique Unique
Index Index
Spatial Spatial
Fulltext Fulltext
Distinct values Distinct values
	6	draw	tinyint(1)			Yes	NULL		Change Change	Drop Drop	
Primary Primary
Unique Unique
Index Index
Spatial Spatial
Fulltext Fulltext
Distinct values Distinct values
	7	paid	tinyint(1)			Yes	NULL		Change Change	Drop Drop	
Primary Primary
Unique Unique
Index Index
Spatial Spatial
Fulltext Fulltext
Distinct values Distinct values
	8	description	text	latin1_swedish_ci		Yes	NULL		Change Change	Drop Drop	
Primary Primary
Unique Unique
Index Index
Spatial Spatial
Fulltext Fulltext
Distinct values Distinct values
	9	duration	int(11)			Yes	NULL		Change Change	Drop Drop	
Primary Primary
Unique Unique
Index Index
Spatial Spatial
Fulltext Fulltext
Distinct values Distinct values
	10	score_own_team	int(11)			Yes	NULL		Change Change	Drop Drop	
Primary Primary
Unique Unique
Index Index
Spatial Spatial
Fulltext Fulltext
Distinct values Distinct values
	11	score_enemy_team	int(11)			Yes	NULL		Change Change	Drop Drop	
Primary Primary
Unique Unique
Index Index
Spatial Spatial
Fulltext Fulltext
Distinct values Distinct values
	12	map_name	varchar(80)	latin1_swedish_ci		Yes	NULL		Change Change	Drop Drop	
Primary Primary
Unique Unique
Index Index
Spatial Spatial
Fulltext Fulltext
Distinct values Distinct values
	13	map_province	varchar(80)	latin1_swedish_ci		Yes	NULL		Change Change	Drop Drop	
Primary Primary
Unique Unique
Index Index
Spatial Spatial
Fulltext Fulltext
Distinct values Distinct values
	14	battle_commander_id	int(11)			Yes	NULL		Change Change	Drop Drop	
Primary Primary
Unique Unique
Index Index
Spatial Spatial
Fulltext Fulltext
Distinct values Distinct values
	15	creator_id	int(11)			Yes	NULL		Change Change	Drop Drop	
Primary Primary
Unique Unique
Index Index
Spatial Spatial
Fulltext Fulltext
Distinct values Distinct values
	16	replay_id	int(11)			Yes	NULL		Change Change	Drop Drop	
Primary Primary
Unique Unique
Index Index
Spatial Spatial
Fulltext Fulltext
Distinct values Distinct values
	17	battle_group_id	int(11)			Yes	NULL		Change Change	Drop Drop	
Primary Primary
Unique Unique
Index Index
Spatial Spatial
Fulltext Fulltext
Distinct values Distinct values
	18	battle_group_final	tinyint(1)			Yes	NULL		Change Change	Drop Drop	
Primary Primary
Unique Unique
Index Index
Spatial Spatial
Fulltext Fulltext
Distinct values Distinct values
	19	stronghold	tinyint(1)			Yes	NULL		Change Change	Drop Drop	
Primary Primary
Unique Unique
Index Index
Spatial Spatial
Fulltext Fulltext
Distinct values Distinct values

**Comment by MACE-Zer0** [comment]
its an old replay .. i dont have a fresh one  , from december , maybe because of that ??? , diferent version from 3.5 could it cause this ??

**Comment by ceari** [comment]
This error should be unrelated to old replays. I just tried to add a replay from November and it worked fine. 

> AttributeError: 'Battle' object has no attribute 'stronghold'

doesn't make sense to me. 
Can you please check if line 138 of /var/www/whyattend/whyattend/model.py is `stronghold = Column(Boolean)`?

**Comment by ceari** [comment]
Got to go now so we'll have to continue tomorrow.  Sorry about these issues but debugging this remotely is tough.

**Comment by MACE-Zer0** [comment]
no problem thanks for helping .. .see ya tomorow !!

**Comment by MACE-Zer0** [comment]
138 - battle_group = relationship("BattleGroup", backref="battles")

**Comment by MACE-Zer0** [comment]
Ok its fixed , i uploaded the model.py fresh from github ... and now everthing is working !! 

Thanks

**Comment by MACE-Zer0** [comment]
Thanks a lot for all your help  XD Great Work
