### ISSUE TITLE
Page "Battles" stay empty

### ISSUE THREAD

**Issue by Tikia** [ceari/whyattend#46]
Hello,

Thanks for this wonderful tools :)

I have an issue with the /battles/list/CLANTAG page, there is not data, see capture.PNG.
![capture](https://cloud.githubusercontent.com/assets/1550241/5891241/fdefea86-a489-11e4-9bed-b30cac99437b.PNG)
I look deeper and found the problem come from the ajax request, server respond : 500 Internal Server Error.
Can't find why... Can you help me ?

Here is the error.log generated :
2015-01-25 06:04:48,721 ERROR: Exception on /battles/list/P4IN2/json [GET] [in /usr/lib/python2.6/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/tikia/clanwars/whyattend/webapp.py", line 152, in decorated_function
    return f(*args, **kwargs)
  File "/home/tikia/clanwars/whyattend/webapp.py", line 956, in battles_list_json
    battle_count = db_session.execute(select([func.count()]).select_from(battles.alias('battles'))).first()[0]
  File "/usr/lib64/python2.6/site-packages/sqlalchemy/orm/scoping.py", line 149, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/lib64/python2.6/site-packages/sqlalchemy/orm/session.py", line 934, in execute
    clause, params or {})
  File "/usr/lib64/python2.6/site-packages/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "/usr/lib64/python2.6/site-packages/sqlalchemy/engine/base.py", line 761, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib64/python2.6/site-packages/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "/usr/lib64/python2.6/site-packages/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
    exc_info
  File "/usr/lib64/python2.6/site-packages/sqlalchemy/util/compat.py", line 195, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/lib64/python2.6/site-packages/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "/usr/lib64/python2.6/site-packages/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) no such function: UUID u'SELECT count(*) AS count_1 \nFROM (SELECT battle.id AS id, battle.date AS date, battle.clan AS clan, battle.enemy_clan AS enemy_clan, battle.victory AS victory, battle.draw AS draw, battle.paid AS paid, battle.description AS description, battle.duration AS duration, battle.score_own_team AS score_own_team, battle.score_enemy_team AS score_enemy_team, battle.map_name AS map_name, battle.map_province AS map_province, battle.battle_commander_id AS battle_commander_id, battle.creator_id AS creator_id, battle.replay_id AS replay_id, battle.battle_group_id AS battle_group_id, battle.battle_group_final AS battle_group_final, CASE WHEN (battle.victory = 1) THEN ? WHEN (battle.draw = 1) THEN ? ELSE ? END AS outcome, ifnull(battle.battle_group_id, UUID()) AS unq_battle_group_id, anon_1.players AS players, anon_2.reserves AS reserves, player.name AS commander_name, player.role AS commander_role, CASE WHEN (battle.id IN (SELECT player_battle.battle_id \nFROM player_battle \nWHERE player_battle.reserve = 0 AND player_battle.player_id = ?)) THEN ? ELSE ? END AS was_player, CASE WHEN (battle.id IN (SELECT player_battle.battle_id \nFROM player_battle \nWHERE player_battle.reserve = 1 AND player_battle.player_id = ?)) THEN ? ELSE ? END AS was_reserve \nFROM battle LEFT OUTER JOIN (SELECT player_battle.battle_id AS battle_id, count(*) AS players \nFROM player_battle \nWHERE player_battle.reserve = 0 GROUP BY player_battle.battle_id) AS anon_1 ON anon_1.battle_id = battle.id LEFT OUTER JOIN (SELECT player_battle.battle_id AS battle_id, count(*) AS reserves \nFROM player_battle \nWHERE player_battle.reserve = 1 GROUP BY player_battle.battle_id) AS anon_2 ON anon_2.battle_id = battle.id LEFT OUTER JOIN player ON player.id = battle.battle_commander_id \nWHERE battle.clan = ? AND (battle.date = (SELECT max(battle_1.date) AS max_1 \nFROM battle AS battle_1 \nWHERE battle.battle_group_id = battle_1.battle_group_id) OR battle.battle_group_id IS NULL) AND 1 AND 1 GROUP BY unq_battle_group_id ORDER BY battle.date DESC) AS battles' ('Victory', 'Draw', 'Defeat', 1, 1, 0, 1, 1, 0, u'P4IN2')

**Comment by ceari** [comment]
Hey, which MySQL version do you use? You can run "mysql --version" to check.

**Comment by Tikia** [comment]
I use sqlite version 3.6.20.
Maybe problem is here, isn't it ?

I also have mysql installed on server : mysql  Ver 14.14 Distrib 5.1.73, for redhat-linux-gnu (x86_64) using readline 5.1
Is it better if i switch ?

**Comment by ceari** [comment]
sqlite doesn't have the UUID function but the tracker should also work with a simple random number function. I'm not sure if there are other things that won't work with sqlite though since I only tested with MySQL.

Can you try changing the "UUID()" to "random()" in the webapp.py in your local installation please: https://github.com/ceari/whyattend/blob/master/whyattend/webapp.py#L914
Remember to restart the webserver after changing it. If it works I'll update the code.

**Comment by Tikia** [comment]
It's working !!!
Thanks you so much :)

**Comment by ceari** [comment]
Great, I updated the code. Thanks for reporting the issue :)

**Comment by Tikia** [comment]
You welcome ;)
