### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by uetam** [ceari/whyattend#48]
When im trying to access /clanwars/statistics/CLAN/players or clanwars/profile in both cases i get Internal Server Error.
Log:
2015-02-15 11:25:42,122 ERROR: Exception on /profile [GET]
Traceback (most recent call last):
  File "/var/www/super/env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/super/env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/super/env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/super/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/super/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/super/whyattend/webapp.py", line 152, in decorated_function
    return f(*args, **kwargs)
  File "/var/www/super/whyattend/webapp.py", line 1843, in profile
    performance = analysis.player_performance(played_battles, [g.player])
  File "/var/www/super/whyattend/analysis.py", line 30, in player_performance
    replay_major_version = int(replay_version_tokens[1])
IndexError: list index out of range
2015-02-15 11:24:52,484 ERROR: Exception on /statistics/5UPER/players [GET]
Traceback (most recent call last):
  File "/var/www/super/env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/super/env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/super/env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/super/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/super/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/super/whyattend/webapp.py", line 152, in decorated_function
    return f(*args, **kwargs)
  File "/var/www/super/whyattend/webapp.py", line 176, in decorated_f
    return f(*args, **kwargs)
  File "/var/www/super/whyattend/webapp.py", line 198, in decorated_f
    return f(*args, **kwargs)
  File "/var/www/super/whyattend/webapp.py", line 1829, in player_performance
    result = analysis.player_performance(battles, players)
  File "/var/www/super/whyattend/analysis.py", line 30, in player_performance
    replay_major_version = int(replay_version_tokens[1])
IndexError: list index out of range

**Comment by ceari** [comment]
Looks like one of your replays has some strange version format. Can you please save the following script as "findreplay.py" file to your tracker installation directory, activate your virtual environment and run it via `python findreplay.py`? https://gist.github.com/ceari/fee8d1fcca4bcd6b274d

**Comment by uetam** [comment]
(myenv)root@domeczek:/var/www/super# python findreplay.py
322
0.9.6.0
323
0.9.6.0
325
0.9.6.0
326
0.9.6.0
327
0.9.6.0
328
0.9.6.0
329
0.9.6.0
330
0.9.6.0
331
0.9.6.0
334
0.9.6.0
335
0.9.6.0
336
0.9.6.0
337
0.9.6.0
338
0.9.6.0
339
0.9.6.0
340
0.9.6.0
341
0.9.6.0
342
0.9.6.0
343
0.9.6.0
344
0.9.6.0
345
0.9.6.0
346
0.9.6.0
347
0.9.6.0

**Comment by ceari** [comment]
Thanks. The format of the version changed in 9.6.0, please try again with the new code.
