### ISSUE TITLE
Problem With calculating gold payout

### ISSUE THREAD

**Issue by MACE-Zer0** [ceari/whyattend#49]
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

here is the log :+1: 

  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/whyattend/whyattend/webapp.py", line 152, in decorated_function
    return f(*args, **kwargs)
  File "/var/www/whyattend/whyattend/webapp.py", line 198, in decorated_f
    return f(*args, **kwargs)
  File "/var/www/whyattend/whyattend/webapp.py", line 176, in decorated_f
    return f(*args, **kwargs)
  File "/var/www/whyattend/whyattend/webapp.py", line 1457, in payout_battles
    points_per_resource = float(request.args.get('points_per_resource'))
TypeError: float() argument must be a string or a number
ERROR:tornado.access:500 GET /payout/MACE/battles?fromDate=01.02.2015&toDate=31.03.2015&gold=0&recruit_factor=1.0 (82.102.2.210) 15.06ms

**Comment by ceari** [comment]
When you go to the payout page there should be an input field for "Points per resource", do you see that?

**Comment by MACE-Zer0** [comment]
nop i only see : 


Battle	Date	Enemy Clan	Added By	Outcome

**Comment by ceari** [comment]
You probably have outdated files. Try updating the whyattend/templates directory with the current one from github.

**Comment by MACE-Zer0** [comment]
thanks that did the trick , outdated templates , thanks and sorry for trouble

**Comment by MACE-Zer0** [comment]
sorry but i noticed another error , cant open the players tab , maybe some more outdated files , take a look 


ERROR:tornado.access:500 GET /statistics/MACE/players (85.139.93.8) 181.34ms
WARNING:tornado.access:404 GET /favicon.ico (85.139.93.8) 3.54ms
ERROR:whyattend.webapp:Exception on /statistics/MACE/players [GET]
Traceback (most recent call last):
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/whyattend/myenv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/whyattend/whyattend/webapp.py", line 152, in decorated_function
    return f(*args, **kwargs)
  File "/var/www/whyattend/whyattend/webapp.py", line 176, in decorated_f
    return f(*args, **kwargs)
  File "/var/www/whyattend/whyattend/webapp.py", line 198, in decorated_f
    return f(*args, **kwargs)
  File "/var/www/whyattend/whyattend/webapp.py", line 1823, in player_performance
    result = analysis.player_performance(battles, players)
  File "/var/www/whyattend/whyattend/analysis.py", line 30, in player_performance
    replay_major_version = int(replay_version_tokens[1])
IndexError: list index out of range
ERROR:tornado.access:500 GET /statistics/MACE/players (85.139.93.8) 176.53ms

**Comment by MACE-Zer0** [comment]
in the statistics / player tab , not the players list  sorrr

**Comment by ceari** [comment]
Probably the same issue as in #48 - The new WoT version changed the replay format slightly but that should be fixed too in the current version. You should always update all files in whyattend/ except for static/img/header.jpg if you use a custom image. Just make a backup of the whole directory before updating and you should be safe.

**Comment by MACE-Zer0** [comment]
ok updated whole whyattend file , left the image header and the config.py , and everthing seams to be working thanks
