### ISSUE TITLE
Problem with stronghold results while trying to use the payout option

### ISSUE THREAD

**Issue by enbewu** [ceari/whyattend#51]
```
WARNING:tornado.access:404 GET /favicon.ico (127.0.0.1) 5.09ms
ERROR:whyattend.webapp:Exception on /payout/PSQD/battles [GET]
Traceback (most recent call last):
  File "/home/cwtracker/cw.psqd.co/cw.psycho/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cwtracker/cw.psqd.co/cw.psycho/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cwtracker/cw.psqd.co/cw.psycho/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cwtracker/cw.psqd.co/cw.psycho/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cwtracker/cw.psqd.co/cw.psycho/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cwtracker/cw.psqd.co/whyattend/webapp.py", line 152, in decorated_function
    return f(*args, **kwargs)
  File "/home/cwtracker/cw.psqd.co/whyattend/webapp.py", line 198, in decorated_f
    return f(*args, **kwargs)
  File "/home/cwtracker/cw.psqd.co/whyattend/webapp.py", line 176, in decorated_f
    return f(*args, **kwargs)
  File "/home/cwtracker/cw.psqd.co/whyattend/webapp.py", line 1493, in payout_battles
    player_resources[ba.player] += ba.resources_earned
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
ERROR:tornado.access:500 GET /payout/PSQD/battles?fromDate=01.04.2015&toDate=30.04.2015&victories_only=on&gold=16000&recruit_factor=0.6&points_per_resource=1 (127.0.0.1) 50.82ms
```

**Comment by ceari** [comment]
I've added a quick fix for the problem but I suspect the stronghold resources earned couldn't be determined from a replay file. Maybe the replay format changed again with a recent patch. I'll have to look into that.

**Comment by enbewu** [comment]
It worked for now
