### ISSUE TITLE
Changes in save files

### ISSUE THREAD

**Issue by enbewu** [ceari/whyattend#52]
```

ERROR:tornado.access:500 POST /battles/create (127.0.0.1) 51.50ms
ERROR:whyattend.webapp:Exception on /battles/create [POST]
Traceback (most recent call last):
  File "/home/cwtracker/cw.psqd.co/cw.psycho/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cwtracker/cw.psqd.co/cw.psycho/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cwtracker/cw.psqd.co/cw.psycho/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cwtracker/cw.psqd.co/cw.psycho/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cwtracker/cw.psqd.co/cw.psycho/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cwtracker/cw.psqd.co/whyattend/webapp.py", line 152, in decorated_function
    return f(*args, **kwargs)
  File "/home/cwtracker/cw.psqd.co/whyattend/webapp.py", line 198, in decorated_f
    return f(*args, **kwargs)
  File "/home/cwtracker/cw.psqd.co/whyattend/webapp.py", line 824, in create_battle
    battle.score_own_team, battle.score_enemy_team = replays.score(replay)
  File "/home/cwtracker/cw.psqd.co/whyattend/replays.py", line 135, in score
    if v['deathReason'] != -1:
TypeError: list indices must be integers, not str
ERROR:tornado.access:500 POST /battles/create (127.0.0.1) 46.65ms
```

**Comment by Gucioo** [comment]
Yep, i have the same:

2015-05-30 14:31:20,734 ERROR: Exception on /battles/create [POST] 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/whyattend-master/whyattend/webapp.py", line 152, in decorated_function
    return f(*args, **kwargs)
  File "/root/whyattend-master/whyattend/webapp.py", line 198, in decorated_f
    return f(*args, **kwargs)
  File "/root/whyattend-master/whyattend/webapp.py", line 824, in create_battle
    battle.score_own_team, battle.score_enemy_team = replays.score(replay)
  File "/root/whyattend-master/whyattend/replays.py", line 135, in score
    if v['deathReason'] != -1:
TypeError: list indices must be integers, not str


And heard that other clans too have this issue, so it seems replay structure was changed in 9.8

**Comment by ceari** [comment]
Thanks for the reports. Let me know if ff50d7a fixes it.
The player performance calculation won't work though, I'll have to take a closer look at that.

**Comment by Gucioo** [comment]
INFO:whyattend.webapp:Querying Wargaming server for battle schedule of clan 500026631 STRNK
/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py:324: Warning: Data truncated for column 'replay_pickle' at row 1
  cursor.execute(statement, parameters)
INFO:whyattend.webapp:Gucio added the battle 608

battle adding working, but cant open recent added battles

ERROR:whyattend.webapp:Exception on /battles/608 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/whyattend-master/whyattend/webapp.py", line 152, in decorated_function
    return f(*args, **kwargs)
  File "/root/whyattend-master/whyattend/webapp.py", line 1048, in battle_details
    return render_template('battles/battle.html', battle=battle, replays=replays)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/whyattend-master/whyattend/templates/battles/battle.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/root/whyattend-master/whyattend/templates/layout.html", line 163, in top-level template code
    {% block content %}{% endblock %}
  File "/root/whyattend-master/whyattend/templates/battles/battle.html", line 128, in block "content"
    {% if battle.replay.unpickle() %}
  File "/root/whyattend-master/whyattend/model.py", line 266, in unpickle
    return pickle.loads(self.replay_pickle)
  File "/usr/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 880, in load_eof
    raise EOFError
EOFError
ERROR:tornado.access:500 GET /battles/608 (89.72.45.232) 108.42ms

**Comment by ceari** [comment]
"Warning: Data truncated for column 'replay_pickle' at row" makes me think  the replay_pickle column in your database is not large enough to hold the data of the first and third example, while the second still fits. Please try running "ALTER TABLE replay MODIFY replay_pickle LONGBLOB" if you are using MySQL and reupload these replays.

**Comment by Gucioo** [comment]
It helps. Thanks for solution. Now all is working as intended.

```
mysql> describe replay;
+----------------------+--------------+------+-----+---------+----------------+
| Field                | Type         | Null | Key | Default | Extra          |
+----------------------+--------------+------+-----+---------+----------------+
| id                   | int(11)      | NO   | PRI | NULL    | auto_increment |
| replay_pickle        | blob         | YES  |     | NULL    |                |
| replay_blob          | longblob     | YES  |     | NULL    |                |
| associated_battle_id | int(11)      | YES  | MUL | NULL    |                |
| player_name          | varchar(100) | YES  |     | NULL    |                |
+----------------------+--------------+------+-----+---------+----------------+
5 rows in set (0.00 sec)
```

```
mysql> alter table replay modify replay_pickle longblob;
Query OK, 623 rows affected (1 min 43.44 sec)
Records: 623  Duplicates: 0  Warnings: 0
```

```
mysql> describe replay;
+----------------------+--------------+------+-----+---------+----------------+
| Field                | Type         | Null | Key | Default | Extra          |
+----------------------+--------------+------+-----+---------+----------------+
| id                   | int(11)      | NO   | PRI | NULL    | auto_increment |
| replay_pickle        | longblob     | YES  |     | NULL    |                |
| replay_blob          | longblob     | YES  |     | NULL    |                |
| associated_battle_id | int(11)      | YES  | MUL | NULL    |                |
| player_name          | varchar(100) | YES  |     | NULL    |                |
+----------------------+--------------+------+-----+---------+----------------+
5 rows in set (0.00 sec)
```
