### ISSUE TITLE
Fix clan member sync broken by API changes

### ISSUE THREAD

**Issue by biurokomplex** [ceari/whyattend#55]
Hello, i update this two files and sync finish without errors right now, but the clan members list on site doesn't open.

jinja2.exceptions.UndefinedError
UndefinedError: 'dict object' has no attribute u'executive_officer'

Traceback (most recent call last)
File "C:\Python27\lib\site-packages\flask\app.py", line 1836, in call
return self.wsgi_app(environ, start_response)
File "C:\Python27\lib\site-packages\flask\app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "C:\Python27\lib\site-packages\flask\app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "C:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "C:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "C:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "C:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
return self.view_functionsrule.endpoint
File "C:\Users\user\Desktop\whyattend\whyattend\webapp.py", line 152, in decorated_function
return f(args, *kwargs)
File "C:\Users\user\Desktop\whyattend\whyattend\webapp.py", line 1187, in clan_players
last_battle_by_player=last_battle_by_player)
File "C:\Python27\lib\site-packages\flask\templating.py", line 128, in render_template
context, ctx.app)
File "C:\Python27\lib\site-packages\flask\templating.py", line 110, in _render
rv = template.render(context)
File "C:\Python27\lib\site-packages\jinja2\environment.py", line 969, in render
return self.environment.handle_exception(exc_info, True)
File "C:\Python27\lib\site-packages\jinja2\environment.py", line 742, in handle_exception
reraise(exc_type, exc_value, tb)
File "C:\Users\user\Desktop\whyattend\whyattend\templates\players\players.html", line 1, in top-level template code
{% extends "layout.html" %}
File "C:\Users\user\Desktop\whyattend\whyattend\templates\layout.html", line 163, in top-level template code
{% block content %}{% endblock %}
File "C:\Users\user\Desktop\whyattend\whyattend\templates\players\players.html", line 70, in block "content"
{{g.roles[player.role]}}
File "C:\Python27\lib\site-packages\markupsafe_native.py", line 22, in escape
return Markup(text_type(s)
UndefinedError: 'dict object' has no attribute u'executive_officer'

And another thing is that the "payment" doesn't show in template.
Do you have any clues?

**Comment by ceari** [comment]
Hi, I added the missing role "executive_officer" to the configuration. If you are using a custom local_config.py make sure to update it (see [config.py](https://github.com/ceari/whyattend/blob/47c0dc4a0ce05628b7ed6b24e5f3b17d8de559fd/whyattend/config.py#L55))

With "payment" you mean the "Gold paid out so far" column in the players table? That's not implemented yet unfortunately: https://github.com/ceari/whyattend/issues/2

**Comment by biurokomplex** [comment]
Thanks for answer, i add this to config, but to make it work i must add too:
'combat_officer': 'combat_officer',
'intelligence_officer': 'intelligence_officer',

Now the clan members show but i stiil dont have a payment (not the "Gold paid out so far") just standard calculator to spend gold...

**Comment by enbewu** [comment]
Furthermore:

```
ERROR:whyattend.webapp:Exception on /sync-players/ [GET]
Traceback (most recent call last):
  File "/home/cwtracker/cw.psqd.co/cw.psycho/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cwtracker/cw.psqd.co/cw.psycho/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cwtracker/cw.psqd.co/cw.psycho/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cwtracker/cw.psqd.co/cw.psycho/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cwtracker/cw.psqd.co/cw.psycho/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cwtracker/cw.psqd.co/whyattend/webapp.py", line 227, in sync_players
    player_ids = clan_info['data'][str(clan_id)]['members'].keys()
AttributeError: 'NoneType' object has no attribute 'keys'
```

**Comment by enbewu** [comment]
After some more issues, local_config.py should have:
```

    'leader': 'Commander',
    'vice_leader': 'Deputy Commander',
    'commander': 'Field Commander',
    'junior_officer': 'Junior Officer',
    'executive_officer': 'Executive Officer',
    'personnel_officer': 'Personnel Officer',
    'combat_officer': 'Combat Officer',
    'recruitment_officer': 'Recr. Officer',
    'intelligence_officer': 'Intelligence Officer',
    'reservist': 'Reservist',
    'recruiter': 'Recruiter',
    'private': 'Soldier',
    'recruit': 'Recruit',
    'treasurer': 'Treasurer',
    'diplomat': 'Diplomat',
```

BUT. WG seems to have changed the rank for Clan Leader and now it's called Commander, not Leader which messes up the in-app access rigths.

**Comment by enbewu** [comment]
To have the ability to pay out you need @biurokomplex to add the new roles to the PAYOUT_ROLE.

**Comment by ceari** [comment]
Thanks for the info @enbewu 

I've updated the defaults in config.py according to https://api.worldoftanks.eu/wgn/clans/glossary/?application_id=demo - it seems the role names changed quite a bit. Let me know if there are roles missing.

**Comment by Gucioo** [comment]
You missed Junior Officer, in ```local_config.py``` should be:
```
ROLE_LABELS = {
    "personnel_officer": "Personnel Officer",
    "quartermaster": "Quartermaster",
    "executive_officer": "Executive Officer",
    "recruit": "Recruit",
    "private": "Private",
    "commander": "Commander",
    "reservist": "Reservist",
    "combat_officer": "Combat Officer",
    "recruitment_officer": "Recruitment Officer",
    "intelligence_officer": "Intelligence Officer",
    "junior_officer": "Junior Officer"
}
```
Sync and players list working fine with that.

**Comment by biurokomplex** [comment]
Hi, all and thanks for help, now all work fine. I have one more question about "profile" when you are login, when you click on your nick and click on "profile" that happend: 
KeyError
KeyError: 0

Traceback (most recent call last)
File "C:\Python27\lib\site-packages\flask\app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "C:\Python27\lib\site-packages\flask\app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "C:\Python27\lib\site-packages\flask\app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "C:\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "C:\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "C:\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "C:\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "C:\Users\user\Desktop\whyattend\whyattend\webapp.py", line 152, in decorated_function
return f(*args, **kwargs)
File "C:\Users\user\Desktop\whyattend\whyattend\webapp.py", line 1837, in profile
performance = analysis.player_performance(played_battles, [g.player])
File "C:\Users\user\Desktop\whyattend\whyattend\analysis.py", line 42, in player_performance
replay_data['second'][0]['players'])
File "C:\Users\user\Desktop\whyattend\whyattend\replays.py", line 163, in player_performance
v = v[0]
KeyError: 0

Do you have the same error? if yes, please give me the clue how to fix it.
Thanks again for all...

**Comment by ceari** [comment]
I implemented some fixes regarding handling of older replay versions that lead to this error. Please try it now.

**Comment by biurokomplex** [comment]
All work fine now. Scheduled Battles, Provinces owned and profiles too. Thanks for help and we can close this topic ;) bye
