### ISSUE TITLE
The battles and province list are not being synced

### ISSUE THREAD

**Issue by enbewu** [ceari/whyattend#56]
WG has created CW2.0 with a completely new map, with battles on different tiers. Since then the old battles and held provinces are not working:

```
ERROR:whyattend.webapp:Error querying WG server for battle schedule
Traceback (most recent call last):
  File "/home/cwtracker/cw.psqd.co/whyattend/webapp.py", line 314, in cached_battle_schedule
    return wotapi.get_battle_schedule(clan_id)
  File "/home/cwtracker/cw.psqd.co/whyattend/wotapi.py", line 125, in get_battle_schedule
    for item in schedule['items']:
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by ceari** [comment]
I tried to fix it, not sure what information is useful now though. What's a "front" anyway? :-)

The API provides the following data:
https://api.worldoftanks.eu/wot/globalmap/clanprovinces/?application_id=demo&clan_id=500021712
and
https://eu.wargaming.net/developers/api_reference/wot/globalmap/clanbattles/ 

Let me know if you want to see other information from there API methods.

**Comment by enbewu** [comment]
The global map has been split into regions (Fronts) which are being played at different tier tanks. I.e. Western Front is being played at 10th tier, Scandinavian Front on 8th tier, Mediterraneran at 6th.

As for the resources there is still good old gold, influence and resources. I don't remember but influence and resources are earned in battles rather than from the provinces themselves.

Provinces are now upgradeable - each has 10 levels, and with next upgrade it earns more gawld.

**Comment by enbewu** [comment]
Personally I think that these are the most crucial info from the API:
```
"front_name": "Scandinavian Front",
"province_name": "Karlskrona"
"arena_name": "Fisherman's Bay",
"prime_time": "19:00",
"daily_revenue": 720,
"revenue_level": 5,
"turns_owned": 358,
```

**Comment by enbewu** [comment]
But I see that you've managed already.
